### ISSUE TITLE
Ability to specify the background image per file

### ISSUE THREAD

**Issue by jamesfoster-excelpoint** [buchizo/ClaudiaIDE#206]
I'd like to be able to set the background images for a file or folder.

For example, when I open `Product.cs` I'd like to see an image of a warehouse, but when I open `Shipment.cs` I'd like to see an image of cargo containers or lorries.

This could be done via a comment in the file
```csharp
// background-image: products.png
``` 

Or, via a config file. This could also be useful if you want a background image for an entire folder. maybe a dotfile like `.background-image`
```
background-image=products.png
```

Or something a bit more structured
```yaml
images:
  - path: source/Model/Products/*
    image: bg/products.png
  - path: source/Api/Shipment.cs
    image: bg/shipment.png
  - path: docs/*
    image: bg/docs.png
```
